services:
  app:
    container_name: app
    build:
      context: ./
      target: app
    tty: true
    depends_on:
      - db
    volumes:
      - ./:/app:rw
    networks:
      - test

  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - test

volumes:
  database_data:

networks:
  test:
